# Generated by Django 6.0.2 on 2026-02-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='siret',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
