# Generated by Django 6.0.2 on 2026-02-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_organization_siret'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='digital_stamp',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/stamps/'),
        ),
    ]
