# Generated by Django 6.0.2 on 2026-02-26 19:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_event_attendees_event_created_by_event_event_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenCaptureSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('work_start', models.TimeField(default='09:00')),
                ('work_end', models.TimeField(default='18:00')),
                ('captures_per_day', models.PositiveIntegerField(default=5)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screen_capture_schedule', to='api.organization')),
            ],
            options={
                'verbose_name': 'Configuration de surveillance',
                'verbose_name_plural': 'Configurations de surveillance',
            },
        ),
        migrations.CreateModel(
            name='ScreenshotCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/%Y/%m/')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='api.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='api.organization')),
            ],
            options={
                'verbose_name': "Capture d'écran",
                'verbose_name_plural': "Captures d'écran",
                'ordering': ['-captured_at'],
            },
        ),
    ]
