# Generated by Django 6.0.2 on 2026-02-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_screencaptureschedule_screenshotcapture'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='current_session_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
